### ISSUE TITLE
Wiki Format

### ISSUE THREAD

**Issue by DeltaDizzy** [DeltaDizzy/Kop-Wiki-Backup#3]
Since Wiki.js has proved unreliable and Thomas has no continued interest in hosting it himself (at least for now), so we should discuss possible options going forward.

- GitHub Pages
- Microsoft Azure (free tier)[1]
- Amazon AWS (free tier)[1]
- other options

[1] With this we would be making the website ourselves using Jekyll (which powers GitHub Pages), Wiki.js, Wordpress, and/or DokuWiki and would just be using this to host it.

**Comment by democat3457** [comment]
Well, I don't think it's Wiki.js itself, it's the server that was hosting Wiki.js. So I think Wiki.js is still a viable alternative.

**Comment by democat3457** [comment]
Also, you have a stray closing ~~bracket~~ parenthesis. :smile:

**Comment by DeltaDizzy** [comment]
So after some more research, I have come to some options:

1. TMSP decides to host something
2. I host one of the wiki softwares on my Raspberry Pi
3. We do GitHub Pages

Microsoft Azure and Amazon AWS both need credit cards, (even for the free tier) and AWS is only free for 12 months. 

If we decidee to do GitHub Pages, we will also need to decide whether or not to use a theme. If we choose GHP and a theme, I think some choices worth looking into would be "Cayman", "Slate", and "Leap Day". We could modify and mix+match appropriately.

**Comment by democat3457** [comment]
Hmm, I don't think TMSP will decide to host something unless we prod him a lot. Also, how easy would hosting the software on your RPi be, and how easy would it be for multiple users to edit the wiki?

**Comment by democat3457** [comment]
In addition, do note that if we use Wiki.js, a cloud-based hosting system will be provided by Wiki.js itself in 2020, allowing for a much easier installation. That's something else to keep in mind.

**Comment by DeltaDizzy** [comment]
Well I dont know how to set it up on the Pi yet, and we should wait until the Wiki.js thing comes out to see if it would work for us or not. In the meantime I have set up a thing that could be used for GitHub pages if we decide to do that.

**Comment by democat3457** [comment]
Alright then, let's use GitHub Pages, then when Wiki.js Cloud comes out, we'll revisit our options.
