### ISSUE TITLE
Body node

### ISSUE THREAD

**Issue by DeltaDizzy** [DeltaDizzy/Kop-Wiki-Backup#5]
It seems we do not have a page for this.

**Comment by democat3457** [comment]
Are you going to make it or me?

**Comment by democat3457** [comment]
Ok then Ill do it

**Comment by DeltaDizzy** [comment]
I was just gonna say we should try to make it adhere to whatever we decide re: https://github.com/DeltaDizzy/Unofficial-Kop-Wiki/issues/4#issuecomment-510683808

**Comment by democat3457** [comment]
Yeah true
